apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngninx-v1
  labels:
    app: nginx-v1
spec:
  replicas: 1
  selector:
    matchLabels:
     app: nginx-v1
  template:
    metadata:
      labels:
        app: nginx-v1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
